version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    # Exclude configs synced from upstream prometheus/prometheus.
    exclude-paths:
      - .github/workflows/container_description.yml
      - .github/workflows/golangci-lint.yml
