go:
    # This must match .circle/config.yml.
    version: 1.15
repository:
    path: github.com/prometheus-community/prom-label-proxy
build:
    binaries:
        - name: prom-label-proxy
    flags: -mod=vendor -tags 'netgo'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - darwin/386
        - windows/amd64
        - windows/386
        - freebsd/amd64
        - freebsd/386
        - openbsd/amd64
        - openbsd/386
        - netbsd/amd64
        - netbsd/386
        - linux/arm
        - linux/arm64
        - freebsd/arm
        - openbsd/arm
        - linux/mips64
        - linux/mips64le
        - netbsd/arm
        - linux/ppc64
        - linux/ppc64le
        - linux/s390x
