---
go:
    # This must match .circle/config.yml.
    version: 1.22
repository:
    path: github.com/prometheus-community/prom-label-proxy
build:
    binaries:
        - name: prom-label-proxy
    # yamllint disable rule:line-length
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
    # yamllint enable rule:line-length
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux
        - darwin
        - windows
        - freebsd
        - openbsd
        - netbsd
